### PR TITLE
Make copy-and-update syntax consistent with records

### PR DESCRIPTION
**Pull request by knocte**
Long records are aligned this way:
```
let rainbow =
    {
        Boss = "Jeffrey"
        Lackeys = [ "Zippy" ; "George" ; "Bungle" ]
    }
```

So copy-and-update syntax should be similar:
```
let rainbow2 =
    {
        rainbow with
            Boss = "Jeffrey"
            Lackeys = [ "Zippy" ; "George" ; "Bungle" ]
    }
```

### CODE REVIEW

**Comment by Smaug123** [comment]
Internally we have a strong convention of:

```fsharp
let rainbow2 =
    { rainbow with
        Boss = "Jeffrey"
        Lackeys = [ "Zippy" ; "George" ; "Bungle" ]
    }
```

**Comment by nojaf** [comment]
In regards to https://github.com/fsprojects/fantomas/issues/1396, we are more wondering if anything changes if the original value is a multiline expression.

Is it
```fsharp
    { GeeTower.Backend.Configuration.GetTestingConfig(
        lndAddress.ToString()
      ) with
        BitcoinRpcUser = "btc"
    }
```

or 
```fsharp
    {
        GeeTower.Backend.Configuration.GetTestingConfig(
            lndAddress.ToString()
        ) with
            BitcoinRpcUser = "btc"
    }
```

I had no intention to challenge the current guide.

**Comment by Smaug123** [comment]
Oh, I see. Both options look really horrible to me :P I'll ping this over to Toby for discussion.

**Comment by TobyShaw** [comment]
I have never seen the record expression in a record update expression be multi line. It's always assigned to an intermediate variable first.

I have no strong opinions on which is chosen to resolve this, since I wouldn't approve any code which contains either expression.

**Comment by nojaf** [comment]
To me, it would seem more consistent to have it like
```fsharp
    { GeeTower.Backend.Configuration.GetTestingConfig(
        lndAddress.ToString()
      ) with
        BitcoinRpcUser = "btc"
    }
```

but indeed, I'd also go for an intermediate variable first.

**Pull request closed without merging**
